version: "3.9"


services:
  # CONTAINER DATABASE POSTGRES
  db:
    image: mdillon/postgis:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: "test"
    
  # GEOSERVER
  geoserver:
    image: kartoza/geoserver:latest
    volumes:
      - /home/tulv:/home/product/
      - /mnt/e/NC/Data:/home/development
      - /mnt:/home/development2
      - geoserver_data:/opt/geoserver/data_dir
    ports:
      - "8002:8080"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s "http://localhost:8080/" || exit 1
      interval: 2m
      timeout: 30s
      retries: 5
      
  # CONTAINER WEB DJANGO
  django:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/duan
    env_file:
      - .env
    command:
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - geoserver

volumes:
  db_data:
    driver: local
  geoserver_data:
    driver: local